### ISSUE TITLE
Прерывания

### ISSUE THREAD

**Issue by murovv** [is-tech-y-24-t7/Processor#8]
Там есть 3 вида прерываний:IRQ, RESET и NMI. Расписать чем они отличаются, реализовать вызов прерываний извне.
Инфа здесь
https://www.nesdev.org/wiki/CPU_interrupts
Посмотри tick-by-tick исполнение.
Если потребуется какая-то запись или чтение из памяти - оставь TODO там

**Comment by rorpo99** [comment]
Reset
Переводит СPU В в изветсное состояние. Регистры устанавливаются на 0x00. Значение счётчика команд считывается из   0xFFFC. Это позволяет перепрпыгнуть на известную програмную локацию в памяти и начать исполняться с неё. Обычно  значение в  0xFFFC устанавливают на время компилляции.
IRQ
 Прерывание происходит только если флаг запрещающий прерывания равен 0. IRQ могут происходить в любое время, но текущая инструкция завершается перед этим и PC хранится на стеке. После того, как прерывание закончено регистр статуса и счётчик команд восставляются до состояния, предшествующего прерыванию. Восстановление происходит из опредленной локации (аналогично Reset)  0xFFFE.
NMI
Похож на IRQ, только это прерывание не может быть проигнорировано и восстановление происходит из 0xFFFА.
