### ISSUE TITLE
Вызов команд

### ISSUE THREAD

**Issue by murovv** [is-tech-y-24-t7/Processor#9]
Надо написать функцию, которая будет инициировать вызов следующей команды. Она будет вызываться извне консолью.
Функция по коду операции определяет ячейку памяти и инструкцию, которая будет вызвана. 
Если там нужно там будет обращение к памяти , пока оставь TODO.
Надо подумать как мы будем конвертировать этот код в вызов инструкции. Для типов адресации вроде как будет енам а что сделать с инструкциями я не знаю.

**Comment by MegaBluejay** [comment]
Имхо не имеет смысла выделять функцию вызова команды.
Поскольку мы всю логику выносим в делегаты, там и так step оч короткий получается, неясно как делить
Если есть идеи пиши
